#!/bin/bash/
echo -e "$COLOR3 $RED.__          _____         ________ $WHITE " 
echo -e "$COLOR3 $RED|__|  ____ _/ ____\____   /  _____/ $WHITE " 
echo -e "$COLOR3 $RED|  | /    \ |  __\/  _ \ /   \  ___ $WHITE  "
echo -e "$COLOR3 $RED|  ||   |  \|  | (  <_> )\    \_\  \ $WHITE "
echo -e "$COLOR3 $RED|__||___|  /|__|  \____/  \______  / $WHITE"
echo -e "$COLOR3 $RED         \/                      \/ $WHITE"  
echo -e "$GREEN[${RED}*$GREEN]${WHITE} developed by IECA [INDIAN ERROR CYBER ARMM]"                                  
echo -e "$GREEN[${RED}*$GREEN]${WHITE} USAGE : Setup InfoG "
echo ""
echo ""

echo -e "$GREEN[${RED}*$GREEN]${WHITE} Installing Dirb "
sudo apt install dirb &> /dev/null
echo -e "$GREEN[${RED}*$GREEN]${WHITE} Installing amass"
sudo apt install amass &> /dev/null
echo -e "$GREEN[${RED}*$GREEN]${WHITE} Installing nmap"
sudo apt install nmap &> /dev/null
clear 
echo "Complete ! !"
exit 0
